name: GBW's build for gh=pages

on:
  push:
    branches:
      - master # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Git LFS
        run: |
          git lfs fetch --all
          git lfs checkout

      - name: Ensure images are not LFS pointers
        run: |
          # Force checkout these files as real files, not pointers
          git lfs pull

          # Verify we have actual files in hugodata
          echo "Checking LFS files in hugodata/static/img:"
          file hugodata/static/img/* | head -10

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Run hugo + manually move site files
        run: |
          # Build the Hugo site
          cd hugodata
          hugo
          
          # Copy generated files from public to root directory
          cp -R public/* ../
          
          # Clean up the public directory
          rm -R -f public

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
          exclude_assets: "README.md,hugodata,sunrisetheme,destijl,.gitignore,*.zip,.gitattributes,.github,*.zip,.claude,TODO.md"
