name: GBW's build for gh=pages

on:
  push:
    branches:
      - master # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Git LFS
        run: |
          git lfs fetch --all
          git lfs checkout

      - name: Ensure images are not LFS pointers
        run: |
          # Create a list of all LFS tracked files
          git lfs track "*.jpg"
          git lfs track "*.png"
          git lfs track "*.gif"

          # Force checkout these files as real files, not pointers
          git lfs pull

          # Verify we have actual files
          file hugoprojects/static/img/*

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Run hugo + manually move site files
        run: |
          rm -f .gitattributes
          rm -R -f project
          mkdir project
          rm -R -f img
          mkdir img
          cp -f -R favicons/ .
          cd hugoprojects
          hugo
          cp -R public/project/* ../project
          cp -R public/img/* ../img
          rm -R -f public

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
          exclude_assets: "README.md,hugoprojects,regenerate_projects.sh,.gitignore,.gitattributes,.github"
