name: Build Changes + Commit to gh-pages branch

on:
  push:
    branches:
      - master # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Git LFS
        run: |
          git lfs fetch --all
          git lfs checkout

      - name: Ensure images are not LFS pointers
        run: |
          # Create a list of all LFS tracked files
          git lfs track "*.jpg"
          git lfs track "*.png"
          git lfs track "*.gif"

          # Force checkout these files as real files, not pointers
          git lfs pull

          # Verify we have actual files
          file hugoprojects/static/img/*

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build Site
        run: |
          rm .gitattributes
          rm -R project
          mkdir project
          rm -R img
          mkdir img
          cd hugoprojects
          hugo
          cp -R public/project/* ../project
          cp -R public/img/* ../img
          rm -R public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
          exclude_assets: "hugoprojects,regenerate_projects.sh,LICENSE,.gitignore,.gitattributes,.github"
